version: "3"
services:
  ploneidg:
    image: unixelias/plone.idg:latest
    depends_on:
      - zeoserver
    environment:
      - ZEO_ADDRESS=zeoserver:8100
    deploy:
      replicas: 2
    ports:
      - 8080:8080

  zeoserver:
    hostname: 'zeoserver'
    image: unixelias/plone.idg:latest
    command: zeoserver
    volumes:
      - plone-data:/data

volumes:
  plone-data:
    external: true
