version: "2"
services:
  varnish:
    hostname: 'varnish'
    image: eeacms/varnish
    restart: 'always'
    depends_on:
      - haproxy
    ports:
      - 8080:6081/tcp
    environment:
      - BACKENDS=haproxy
      - BACKENDS_PORT=5000
      - BACKENDS_PROBE_INTERVAL=3s
      - BACKENDS_PROBE_THRESHOLD=2
      - BACKENDS_PROBE_TIMEOUT=1s
      - BACKENDS_PROBE_WINDOW=3
      - DNS_ENABLED=true

  haproxy:
    image: eeacms/haproxy
    restart: 'always'
    depends_on:
      - ploneidg
    ports:
      - 1936:1936
    environment:
      - BACKENDS=ploneidg
      - BACKENDS_PORT=8080
      - SERVICE_NAMES=ploneidg
      - DNS_ENABLED=true
      - STATS_AUTH=admin:admin

  zeoserver:
    hostname: 'zeoserver'
    image: unixelias/plone.idg
    command:
      - zeoserver
    volumes:
      - data:/data
    environment:
      - ZEO_SHARED_BLOB_DIR=on

  ploneidg:
    image: unixelias/plone.idg
    depends_on:
      - zeoserver
    environment:
      - ZEO_ADDRESS=zeoserver:8100
volumes:
  data:
