version: "3"
services:

  haproxy:
    image: eeacms/haproxy
    restart: 'always'
    depends_on:
      - ploneidg
    ports:
      - 8080:5000
      - 1936:1936
    environment:
      - BACKENDS=ploneidg
      - BACKENDS_PORT=8080
      - SERVICE_NAMES=ploneidg

  ploneidg:
    image: unixelias/plone.idg:latest
    depends_on:
      - zeoserver
    environment:
      - ZEO_ADDRESS=zeoserver:8100

  zeoserver:
    hostname: 'zeoserver'
    image: unixelias/plone.idg:latest
    command: zeoserver
    volumes:
      - data:/data

volumes:
  data:
    driver: local
    driver_opts:
      mountpoint: /srv/portal/data
      command: chown -R 500:500 /data
