version: "3"
services:
  haproxy:
    image: eeacms/haproxy
    restart: 'always'
    ports:
    - 8080:5000
    - 1936:1936
    links:
    - ploneidg
    environment:
    - BACKENDS_PORT=8080
    - SERVICE_NAMES=plone

  ploneidg:
    image: unixelias/plone.idg:latest
    links:
    - zeoserver
    volumes:
    - data:/data
    environment:
    - ZEO_ADDRESS=zeoserver:8100

  zeoserver:
    hostname: 'zeoserver'
    image: unixelias/plone.idg:latest
    command: zeoserver
    volumes:
    - datazeo:/data
    environment:
    - ZEO_SHARED_BLOB_DIR=on

volumes:
  data:
    driver: local-persist
    driver_opts:
      mountpoint: ./data
      command: chown -R 500:500 /data
  datazeo:
    driver: local-persist
    driver_opts:
      mountpoint: ./datazeo
      command: chown -R 500:500 /data
